#ifndef REGISTRY_H
#define REGISTRY_H

// We must declare, not define, function pointers in the header.  Otherwise, linker fails.
// Function pointers.
extern LONG (WINAPI* pRegOpenKeyExA)(HKEY hKey,
							 LPCSTR lpSubKey,
							 DWORD ulOptions,
							 REGSAM samDesired,
							 PHKEY phkResult);
extern LONG (WINAPI* pRegOpenKeyExW)(HKEY hKey,
							 LPCWSTR lpSubKey,
							 DWORD ulOptions,
							 REGSAM samDesired,
							 PHKEY phkResult);
extern LONG (WINAPI* pRegCreateKeyExA)(HKEY hKey,
								LPCSTR lpSubKey,
								DWORD Reserved,
								LPSTR lpClass,
								DWORD dwOptions,
								REGSAM samDesired,
								LPSECURITY_ATTRIBUTES lpSecurityAttributes,
								PHKEY phkResult,
								LPDWORD lpdwDisposition);
extern LONG (WINAPI* pRegCreateKeyExW)(HKEY hKey,
								LPCWSTR lpSubKey,
								DWORD Reserved,
								LPWSTR lpClass,
								DWORD dwOptions,
								REGSAM samDesired,
								LPSECURITY_ATTRIBUTES lpSecurityAttributes,
								PHKEY phkResult,
								LPDWORD lpdwDisposition);
extern LONG (WINAPI* pRegDeleteKeyExA)(HKEY hKey,
							  LPCSTR lpSubKey,
							  REGSAM samDesired,
							  DWORD Reserved);
extern LONG (WINAPI* pRegDeleteKeyExW)(HKEY hKey,
							  LPCWSTR lpSubKey,
							  REGSAM samDesired,
							  DWORD Reserved);
extern LONG (WINAPI* pRegQueryValueExA)(HKEY hKey,
								LPCSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
extern LONG (WINAPI* pRegQueryValueExW)(HKEY hKey,
								LPCWSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
extern LONG (WINAPI* pRegEnumKeyExA)(HKEY hKey,
								DWORD dwIndex,
								LPSTR lpName,
								LPDWORD lpcName,
								LPDWORD lpReserved,
								LPSTR lpClass,
								LPDWORD lpcClass,
								PFILETIME lpftLastWriteTime);
extern LONG (WINAPI* pRegEnumKeyExW)(HKEY hKey,
								DWORD dwIndex,
								LPWSTR lpName,
								LPDWORD lpcName,
								LPDWORD lpReserved,
								LPWSTR lpClass,
								LPDWORD lpcClass,
								PFILETIME lpftLastWriteTime);
extern LONG (WINAPI* pRegGetValueA)(HKEY hKey,
							LPCSTR lpSubKey,
							LPCSTR lpValue,
							DWORD dwFlags,
							LPDWORD pdwType,
							PVOID pvData,
							LPDWORD pcbData);
extern LONG (WINAPI* pRegGetValueW)(HKEY hKey,
							LPCWSTR lpSubKey,
							LPCWSTR lpValue,
							DWORD dwFlags,
							LPDWORD pdwType,
							PVOID pvData,
							LPDWORD pcbData);
extern LONG (WINAPI* pRegSetValueExA)(HKEY hKey,
							LPCSTR lpValueName,
							DWORD Reserved,
							DWORD dwType,
							const BYTE* lpData,
							DWORD cbData);
extern LONG (WINAPI* pRegSetValueExW)(HKEY hKey,
							LPCWSTR lpValueName,
							DWORD Reserved,
							DWORD dwType,
							const BYTE* lpData,
							DWORD cbData);

// Hooked Functions.
LONG WINAPI hooked_RegOpenKeyExA(HKEY hKey,
							 LPCSTR lpSubKey,
							 DWORD ulOptions,
							 REGSAM samDesired,
							 PHKEY phkResult);
LONG WINAPI hooked_RegOpenKeyExW(HKEY hKey,
							 LPCWSTR lpSubKey,
							 DWORD ulOptions,
							 REGSAM samDesired,
							 PHKEY phkResult);
LONG WINAPI hooked_RegCreateKeyExA(HKEY hKey,
								LPCSTR lpSubKey,
								DWORD Reserved,
								LPSTR lpClass,
								DWORD dwOptions,
								REGSAM samDesired,
								LPSECURITY_ATTRIBUTES lpSecurityAttributes,
								PHKEY phkResult,
								LPDWORD lpdwDisposition);
LONG WINAPI hooked_RegCreateKeyExW(HKEY hKey,
								LPCWSTR lpSubKey,
								DWORD Reserved,
								LPWSTR lpClass,
								DWORD dwOptions,
								REGSAM samDesired,
								LPSECURITY_ATTRIBUTES lpSecurityAttributes,
								PHKEY phkResult,
								LPDWORD lpdwDisposition);
LONG WINAPI hooked_RegDeleteKeyExA(HKEY hKey,
							  LPCSTR lpSubKey,
							  REGSAM samDesired,
							  DWORD Reserved);
LONG WINAPI hooked_RegDeleteKeyExW(HKEY hKey,
							  LPCWSTR lpSubKey,
							  REGSAM samDesired,
							  DWORD Reserved);
LONG WINAPI hooked_RegQueryValueExA(HKEY hKey,
								LPCSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
LONG WINAPI hooked_RegQueryValueExW(HKEY hKey,
								LPCWSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
LONG WINAPI hooked_RegEnumKeyExA(HKEY hKey,
								DWORD dwIndex,
								LPSTR lpName,
								LPDWORD lpcName,
								LPDWORD lpReserved,
								LPSTR lpClass,
								LPDWORD lpcClass,
								PFILETIME lpftLastWriteTime);
LONG WINAPI hooked_RegEnumKeyExW(HKEY hKey,
								DWORD dwIndex,
								LPWSTR lpName,
								LPDWORD lpcName,
								LPDWORD lpReserved,
								LPWSTR lpClass,
								LPDWORD lpcClass,
								PFILETIME lpftLastWriteTime);
LONG WINAPI hooked_RegGetValueA(HKEY hKey,
							LPCSTR lpSubKey,
							LPCSTR lpValue,
							DWORD dwFlags,
							LPDWORD pdwType,
							PVOID pvData,
							LPDWORD pcbData);
LONG WINAPI hooked_RegGetValueW(HKEY hKey,
							LPCWSTR lpSubKey,
							LPCWSTR lpValue,
							DWORD dwFlags,
							LPDWORD pdwType,
							PVOID pvData,
							LPDWORD pcbData);
LONG WINAPI hooked_RegSetValueExA(HKEY hKey,
							LPCSTR lpValueName,
							DWORD Reserved,
							DWORD dwType,
							const BYTE* lpData,
							DWORD cbData);
LONG WINAPI hooked_RegSetValueExW(HKEY hKey,
							LPCWSTR lpValueName,
							DWORD Reserved,
							DWORD dwType,
							const BYTE* lpData,
							DWORD cbData);
LONG WINAPI hooked_RegOpenKeyEx(HKEY hKey,
							 LPCTSTR lpSubKey,
							 DWORD ulOptions,
							 REGSAM samDesired,
							 PHKEY phkResult);
LONG WINAPI hooked_RegCreateKeyEx(HKEY hKey,
								LPCTSTR lpSubKey,
								DWORD Reserved,
								LPTSTR lpClass,
								DWORD dwOptions,
								REGSAM samDesired,
								LPSECURITY_ATTRIBUTES lpSecurityAttributes,
								PHKEY phkResult,
								LPDWORD lpdwDisposition);
LONG WINAPI hooked_RegDeleteKeyEx(HKEY hKey,
							  LPCTSTR lpSubKey,
							  REGSAM samDesired,
							  DWORD Reserved);
LONG WINAPI hooked_RegQueryValueExA(HKEY hKey,
								LPCSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
LONG WINAPI hooked_RegQueryValueExW(HKEY hKey,
								LPCWSTR lpValueName,
								LPDWORD lpReserved,
								LPDWORD lpType,
								LPBYTE lpData,
								LPDWORD lpcbData);
LONG WINAPI hooked_RegEnumKeyEx(HKEY hKey,
								DWORD dwIndex,
								LPTSTR lpName,
								LPDWORD lpcName,
								LPDWORD lpReserved,
								LPTSTR lpClass,
								LPDWORD lpcClass,
								PFILETIME lpftLastWriteTime);
LONG WINAPI hooked_RegGetValue(HKEY hKey,
							LPCTSTR lpSubKey,
							LPCTSTR lpValue,
							DWORD dwFlags,
							LPDWORD pdwType,
							PVOID pvData,
							LPDWORD pcbData);
LONG WINAPI hooked_RegSetValueEx(HKEY hKey,
							LPCTSTR lpValueName,
							DWORD Reserved,
							DWORD dwType,
							const BYTE* lpData,
							DWORD cbData);
#endif